// ─── Owner Command V3 — Legacy Route Catalog ──────────────────────────────
// Extracted from src/App.jsx admin routes. All routes preserved — none removed.
// Each route is categorized by workspace and classified for future consolidation.

function r(path, workspace, classification, inSidebar, recommendation) {
  const label = path
    .replace('/admin/', '')
    .split('/')
    .pop()
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
  return { path, label, workspace, classification, inSidebar, recommendation };
}

export const WORKSPACES = [
  'Today', 'Music and Mastering', 'Content and Publishing', 'Store and Fulfilment',
  'Coaching and Clients', 'Fans and Support', 'Money and Payments', 'Systems and Approvals',
];

export const LEGACY_ROUTES = [
  // ─── Today ───────────────────────────────────────────────────────────────
  r('/admin/dashboard', 'Today', 'primary', true, 'keep'),
  r('/admin/dashboard-v2', 'Today', 'specialist', false, 'investigate'),
  r('/admin/owner-command-v3', 'Today', 'primary', true, 'keep'),
  r('/admin/mission-control', 'Today', 'specialist', true, 'investigate'),
  r('/admin/priority-commander', 'Today', 'specialist', true, 'investigate'),
  r('/admin/human-action-required', 'Today', 'specialist', true, 'keep'),
  r('/admin/launch-content', 'Today', 'specialist', true, 'investigate'),
  r('/admin/owner-business', 'Today', 'specialist', true, 'investigate'),

  // ─── Music and Mastering ────────────────────────────────────────────────
  r('/admin/releases', 'Music and Mastering', 'primary', true, 'keep'),
  r('/admin/mastering', 'Music and Mastering', 'primary', true, 'keep'),
  r('/admin/release-sprint', 'Music and Mastering', 'primary', true, 'keep'),
  r('/admin/release-countdown', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/release-promo-command', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/music-command', 'Music and Mastering', 'specialist', true, 'merge'),
  r('/admin/music-opportunity-bulletin', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/sync-licensing-command', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/tunecore', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/distributors', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/lyrics-archive', 'Music and Mastering', 'primary', true, 'keep'),
  r('/admin/mums-garden', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/mum', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/without-you-here', 'Music and Mastering', 'duplicate_candidate', true, 'redirect'),
  r('/admin/memorial', 'Music and Mastering', 'specialist', true, 'keep'),
  r('/admin/merch-reel', 'Music and Mastering', 'specialist', true, 'investigate'),
  r('/admin/music-fan', 'Music and Mastering', 'specialist', true, 'investigate'),

  // ─── Content and Publishing ──────────────────────────────────────────────
  r('/admin/content-studio', 'Content and Publishing', 'primary', true, 'keep'),
  r('/admin/social-content', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/content-dashboard', 'Content and Publishing', 'specialist', true, 'merge'),
  r('/admin/content-command-centre', 'Content and Publishing', 'specialist', false, 'merge'),
  r('/admin/content-command', 'Content and Publishing', 'specialist', false, 'merge'),
  r('/admin/content-automate', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/content-to-cash', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/content-quality-review', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/content-performance', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-command', 'Content and Publishing', 'specialist', true, 'merge'),
  r('/admin/social-monitor', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-intelligence', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-agent-os', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/social-post-factory', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-asset-library', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-schedule-queue', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-platform-parity', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/social-oauth-command', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-review-readiness', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/social-content-readiness', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/social-analytics-command', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/social-distribution-readiness', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/social-drafts', 'Content and Publishing', 'specialist', true, 'merge'),
  r('/admin/instagram-sync', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/instagram-story-studio', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/instagram-auto-dm-command', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/manychat-drafts', 'Content and Publishing', 'primary', true, 'keep'),
  r('/admin/daily-post-engine', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/trend-monitor', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/creator-insights', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/ideas-engine', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/creative-studio', 'Content and Publishing', 'specialist', true, 'investigate'),
  r('/admin/marketing-centre', 'Content and Publishing', 'specialist', true, 'merge'),
  r('/admin/announcement-studio', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/campaign-image-approval', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/metricool-command', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/metricool-api-setup', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/metricool-media-pipeline', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/metricool-scheduler-queue', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/metricool-performance-intelligence', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/metricool-diagnostics', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/video-agent-command', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/videos', 'Content and Publishing', 'specialist', true, 'keep'),
  r('/admin/livestream-command', 'Content and Publishing', 'specialist', true, 'keep'),

  // ─── Store and Fulfilment ────────────────────────────────────────────────
  r('/admin/merch', 'Store and Fulfilment', 'primary', true, 'keep'),
  r('/admin/orders', 'Store and Fulfilment', 'primary', true, 'keep'),
  r('/admin/store-orders', 'Store and Fulfilment', 'specialist', true, 'merge'),
  r('/admin/merch-designs', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/merch-platforms', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/merch-financials', 'Store and Fulfilment', 'specialist', true, 'merge'),
  r('/admin/merch-visual-lab', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/merch-feedback', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/merch-content-briefs', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/print-fulfilment', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/procurement-command', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/landed-cost-calculator', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/stock-flow-dashboard', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/shipping-rates', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/promo-codes', 'Store and Fulfilment', 'primary', true, 'keep'),
  r('/admin/promo-code-audit', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/discount-guard', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/promo-discount-compliance', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/pricing-margin-calculator', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/bundle-proposal-studio', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/offer-engine', 'Store and Fulfilment', 'specialist', true, 'investigate'),
  r('/admin/product-insights', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/image-editor', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/quick-upload', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/thank-you-cards', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/hoodie-offer', 'Store and Fulfilment', 'specialist', true, 'investigate'),
  r('/admin/gift-claims', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/gift-verification', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/gift-progress', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/reveal-newsletter', 'Store and Fulfilment', 'specialist', true, 'keep'),
  r('/admin/ecommerce-intelligence', 'Store and Fulfilment', 'specialist', true, 'merge'),
  r('/admin/ecommerce-command', 'Store and Fulfilment', 'specialist', true, 'merge'),

  // ─── Coaching and Clients ────────────────────────────────────────────────
  r('/admin/coaching', 'Coaching and Clients', 'primary', true, 'keep'),
  r('/admin/coaching-hub', 'Coaching and Clients', 'primary', true, 'keep'),
  r('/admin/coaching-overview', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-leads', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-intakes', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-clients', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-command', 'Coaching and Clients', 'specialist', true, 'merge'),
  r('/admin/coaching-launch-control', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-programs', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-legal', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-content-library', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-content-engine', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-roi', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching-sales-funnel', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/meditation-library', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/client-management', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/appointment-scheduler', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/workbook-builder', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/client-resource-library', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/client-onboarding', 'Coaching and Clients', 'specialist', true, 'keep'),
  r('/admin/coaching/self-worth-reset', 'Coaching and Clients', 'specialist', false, 'keep'),
  r('/admin/coaching/boundaries', 'Coaching and Clients', 'specialist', false, 'keep'),
  r('/admin/coaching/creative-confidence', 'Coaching and Clients', 'specialist', false, 'keep'),
  r('/admin/coaching/workbooks', 'Coaching and Clients', 'specialist', false, 'keep'),
  r('/admin/coaching/intake', 'Coaching and Clients', 'specialist', false, 'keep'),
  r('/admin/coaching/client-resources', 'Coaching and Clients', 'specialist', false, 'keep'),
  r('/admin/training', 'Coaching and Clients', 'specialist', true, 'merge'),
  r('/admin/training-centre', 'Coaching and Clients', 'specialist', true, 'merge'),
  r('/admin/education-hub', 'Coaching and Clients', 'specialist', true, 'merge'),
  r('/admin/sales-training', 'Coaching and Clients', 'specialist', true, 'keep'),

  // ─── Fans and Support ───────────────────────────────────────────────────
  r('/admin/fans', 'Fans and Support', 'primary', true, 'keep'),
  r('/admin/subscribers', 'Fans and Support', 'primary', true, 'keep'),
  r('/admin/supporters', 'Fans and Support', 'primary', true, 'keep'),
  r('/admin/fan-media', 'Fans and Support', 'specialist', true, 'keep'),
  r('/admin/newsletter', 'Fans and Support', 'specialist', true, 'keep'),
  r('/admin/communications-hub', 'Fans and Support', 'primary', true, 'keep'),
  r('/admin/phone-system', 'Fans and Support', 'specialist', true, 'keep'),
  r('/admin/business-attention-centre', 'Fans and Support', 'specialist', true, 'merge'),
  r('/admin/notifications', 'Fans and Support', 'specialist', true, 'merge'),
  r('/admin/fan-conversion-engine', 'Fans and Support', 'specialist', true, 'investigate'),
  r('/admin/growth-engine', 'Fans and Support', 'specialist', true, 'investigate'),
  r('/admin/executive-feed', 'Fans and Support', 'specialist', true, 'investigate'),

  // ─── Money and Payments ─────────────────────────────────────────────────
  r('/admin/financials', 'Money and Payments', 'primary', true, 'keep'),
  r('/admin/payment-diagnostics', 'Money and Payments', 'primary', true, 'keep'),
  r('/admin/stripe-command-centre', 'Money and Payments', 'primary', true, 'keep'),
  r('/admin/stripe-live-report', 'Money and Payments', 'specialist', true, 'merge'),
  r('/admin/webhook-health', 'Money and Payments', 'specialist', true, 'keep'),
  r('/admin/revenue-command', 'Money and Payments', 'specialist', true, 'merge'),
  r('/admin/revenue-actions', 'Money and Payments', 'specialist', true, 'keep'),
  r('/admin/agent-revenue-status', 'Money and Payments', 'specialist', true, 'keep'),
  r('/admin/order-profit-intelligence', 'Money and Payments', 'specialist', true, 'keep'),
  r('/admin/charity-tracking', 'Money and Payments', 'specialist', true, 'keep'),
  r('/admin/weekly-money-report', 'Money and Payments', 'specialist', true, 'keep'),
  r('/admin/todays-money-moves', 'Money and Payments', 'specialist', true, 'investigate'),
  r('/admin/business-worth-command', 'Money and Payments', 'specialist', true, 'investigate'),
  r('/admin/intelligence-to-income', 'Money and Payments', 'specialist', true, 'investigate'),
  r('/admin/wealth-dashboard', 'Money and Payments', 'specialist', true, 'investigate'),
  r('/admin/report', 'Money and Payments', 'specialist', true, 'keep'),

  // ─── Systems and Approvals ──────────────────────────────────────────────
  r('/admin/approval-queue', 'Systems and Approvals', 'primary', true, 'keep'),
  r('/admin/command-centre', 'Systems and Approvals', 'specialist', true, 'merge'),
  r('/admin/agent-registry', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-task-log', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-workbench', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-intelligence', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-learning', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-capability-matrix', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-tool-registry', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-message-bus', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/agent-trust-hub', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/memory-graph', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/self-healing', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/autonomous-ops', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/autonomous-repair-loop', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/knowledge-vault', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/risk-alerts', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/security-centre', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/security-trust-centre', 'Systems and Approvals', 'duplicate_candidate', true, 'redirect'),
  r('/admin/norton-safe-web-guide', 'Systems and Approvals', 'duplicate_candidate', true, 'redirect'),
  r('/admin/audit-log', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/operational-status', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/site-health', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/site-function-audit', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/site-upgrade-audit', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/website-ops', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/website-evolution', 'Systems and Approvals', 'specialist', true, 'investigate'),
  r('/admin/click-audit', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/link-integrity-audit', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/api-setup', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/integration-action-centre', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/integration-completion-centre', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/go-live', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/system-blueprint', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/master-blueprint', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/blueprint-builder', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/blueprint', 'Systems and Approvals', 'specialist', false, 'investigate'),
  r('/admin/operation-registry', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/external-engineering-command', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/cursor-cloud-agent-command', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/openai-command', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/code-audit-command', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/code-audit-export', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/chatgpt-code-review-export', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/developer-handoff', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/qa-command-centre', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/playwright-test-centre', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/qa-failure-report', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/voice-input-test', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/ai-cost-control', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/final-system-status', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/final-system-report', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/guided-setup-concierge', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/base44-exit-plan', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/orchestrator-chat', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/legal-dashboard', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/legal-drafts', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/ganozmix-direct/legal', 'Systems and Approvals', 'duplicate_candidate', true, 'redirect'),
  r('/admin/research-hub', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/research-grid', 'Systems and Approvals', 'specialist', true, 'merge'),
  r('/admin/business-profile-settings', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/settings/business-details', 'Systems and Approvals', 'duplicate_candidate', true, 'redirect'),
  r('/admin/settings', 'Systems and Approvals', 'primary', true, 'keep'),
  r('/admin/premium-ux', 'Systems and Approvals', 'specialist', true, 'investigate'),
  r('/admin/business-process-command', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/artist-business-setup', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/strategic-execution-plan', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/monthly-monitoring', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/client-installs', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/systems-qa', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/automation-agents', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/tiktok-review', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/tiktok-screen-guide', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/tiktok-platform-review', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/tiktok-recording-studio', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/press-kit', 'Systems and Approvals', 'specialist', true, 'keep'),
  r('/admin/ganozmix', 'Systems and Approvals', 'specialist', true, 'keep'),
];

// Stats helper
export function getRouteStats() {
  const total = LEGACY_ROUTES.length;
  const byWorkspace = {};
  const byClassification = {};
  const inSidebar = LEGACY_ROUTES.filter(r => r.inSidebar).length;
  LEGACY_ROUTES.forEach(route => {
    byWorkspace[route.workspace] = (byWorkspace[route.workspace] || 0) + 1;
    byClassification[route.classification] = (byClassification[route.classification] || 0) + 1;
  });
  return { total, byWorkspace, byClassification, inSidebar, notInSidebar: total - inSidebar };
}