// Canonical static agent registry — used as fallback when DB returns empty.
// These are the base definitions for the Gannon Waye AI Operating System.

export const AGENT_REGISTRY_SEED = [
  // PERSONAL
  { agent_name: 'Daily Briefing Agent', group: 'personal', purpose: 'Delivers a morning summary of priority tasks, schedule, risks, and opportunities.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Calendar Intelligence Agent', group: 'personal', purpose: 'Monitors, organises, and optimises calendar events and scheduling conflicts.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Goal Tracking Agent', group: 'personal', purpose: 'Tracks personal and professional goals with milestone check-ins and nudges.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Health & Wellness Agent', group: 'personal', purpose: 'Monitors energy, sleep, and wellness patterns. Surfaces patterns and flags burnout risk.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Travel Logistics Agent', group: 'personal', purpose: 'Plans and coordinates travel, transfers, accommodation, and touring logistics.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Personal Finance Tracker', group: 'personal', purpose: 'Tracks personal income, expenses, and savings goals across accounts.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Relationship CRM Agent', group: 'personal', purpose: 'Maintains notes and follow-up reminders for key personal and professional relationships.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Mindset Journal Agent', group: 'personal', purpose: 'Prompts daily reflection, surfaces mood patterns, and flags persistent negative states.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },

  // COMMUNICATION
  { agent_name: 'Email Triage Agent', group: 'communication', purpose: 'Categorises, prioritises, and drafts responses to incoming emails.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'low' },
  { agent_name: 'Fan Reply Agent', group: 'communication', purpose: 'Drafts warm, on-brand replies to fan messages across email and social DMs.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Newsletter Drafting Agent', group: 'communication', purpose: 'Drafts fan newsletters based on recent events, releases, and campaign goals.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Booking Enquiry Agent', group: 'communication', purpose: 'Screens and responds to booking enquiries with templated negotiation logic.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'medium', reputation_risk: 'medium' },
  { agent_name: 'Press & Media Agent', group: 'communication', purpose: 'Monitors press mentions, drafts media responses, and flags interview requests.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'high' },
  { agent_name: 'Collaboration Outreach Agent', group: 'communication', purpose: 'Researches and drafts outreach messages to potential collaborators, sync partners, and brands.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'low', legal_risk: 'low', reputation_risk: 'medium' },
  { agent_name: 'Crisis Communication Agent', group: 'communication', purpose: 'Drafts holding statements and escalation paths when reputational issues arise.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'high' },

  // LEGAL
  { agent_name: 'Contract Review Agent', group: 'legal', purpose: 'Flags unusual clauses, rights grabs, and risk items in contracts before human review.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'medium' },
  { agent_name: 'Rights Management Agent', group: 'legal', purpose: 'Tracks music rights, licensing agreements, and ownership splits.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'none' },
  { agent_name: 'Royalty Monitoring Agent', group: 'legal', purpose: 'Monitors royalty statements from distributors and flags discrepancies.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'medium', legal_risk: 'medium', reputation_risk: 'none' },
  { agent_name: 'IP Protection Agent', group: 'legal', purpose: 'Monitors for unauthorised use of name, likeness, music, and brand across platforms.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Tax Compliance Agent', group: 'legal', purpose: 'Tracks deductible expenses and flags upcoming tax obligations. Does not file.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'none' },
  { agent_name: 'LGBTQIA+ Protections Agent', group: 'legal', purpose: 'Monitors legal landscape for LGBTQIA+ protections and flags relevant legal changes or risks.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'medium' },
  { agent_name: 'NDAs & Confidentiality Agent', group: 'legal', purpose: 'Tracks active NDAs, expiry dates, and breach risks.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'high', reputation_risk: 'high' },

  // RESEARCH
  { agent_name: 'Music Industry Intelligence Agent', group: 'research', purpose: 'Monitors music industry trends, deal structures, and competitor releases.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Platform Algorithm Agent', group: 'research', purpose: 'Researches and synthesises platform algorithm changes across Spotify, TikTok, IG, and YouTube.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Fan Sentiment Agent', group: 'research', purpose: 'Analyses fan comments, DMs, and reviews to surface sentiment trends.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Competitive Analysis Agent', group: 'research', purpose: 'Tracks comparable artists and identifies positioning opportunities.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Sync Licensing Research Agent', group: 'research', purpose: 'Identifies sync licensing opportunities in TV, film, and advertising.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'low', legal_risk: 'low', reputation_risk: 'none' },
  { agent_name: 'Grant & Funding Research Agent', group: 'research', purpose: 'Researches arts grants, government funding, and creative industry programs.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Cultural Trend Agent', group: 'research', purpose: 'Monitors broader cultural conversations relevant to the artist brand and output.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'LGBTQIA+ Culture Monitor', group: 'research', purpose: 'Tracks cultural, political, and media shifts in LGBTQIA+ spaces globally.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },

  // CREATIVE
  { agent_name: 'Lyric Drafting Agent', group: 'creative', purpose: 'Assists with lyric brainstorming, rhyme schemes, and hook development.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'medium' },
  { agent_name: 'Creative Direction Agent', group: 'creative', purpose: 'Develops visual and conceptual direction for releases, videos, and campaigns.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Cover Art Brief Agent', group: 'creative', purpose: 'Generates detailed briefs for cover art designers based on track mood and brand.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Music Video Concept Agent', group: 'creative', purpose: 'Develops music video treatments, shot lists, and director briefs.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Press Kit Agent', group: 'creative', purpose: 'Maintains and updates EPK content including bio, photos, and quotes.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Merchandise Design Brief Agent', group: 'creative', purpose: 'Generates merch design briefs aligned with release and campaign aesthetics.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Sample Clearance Research Agent', group: 'creative', purpose: 'Identifies sample usage and flags clearance requirements before production.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'high', reputation_risk: 'none' },

  // WEBSITE
  { agent_name: 'Site Health Monitor', group: 'website', purpose: 'Runs automated health checks on site performance, broken links, and uptime.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'SEO Audit Agent', group: 'website', purpose: 'Audits site SEO, meta tags, and structured data. Drafts improvement recommendations.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Content Update Agent', group: 'website', purpose: 'Flags outdated content, broken media, and expired offers on the public site.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Store Ops Agent', group: 'website', purpose: 'Monitors low stock, pending orders, and shipping delays. Alerts admin on anomalies.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Fan Portal Agent', group: 'website', purpose: 'Manages fan registration, portal access, and community moderation flagging.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'medium' },
  { agent_name: 'Analytics Digest Agent', group: 'website', purpose: 'Compiles weekly analytics summaries across site, store, and streaming.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },

  // MARKETING
  { agent_name: 'Release Campaign Agent', group: 'marketing', purpose: 'Plans and executes multi-channel release campaigns including timelines and asset schedules.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Email Campaign Agent', group: 'marketing', purpose: 'Plans, drafts, and schedules email campaigns to subscriber segments.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'medium' },
  { agent_name: 'Paid Ads Agent', group: 'marketing', purpose: 'Researches ad strategies and drafts campaign briefs for Meta, TikTok, and YouTube ads.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Playlist Pitching Agent', group: 'marketing', purpose: 'Identifies playlist curators and drafts personalised pitches for new releases.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Brand Partnership Agent', group: 'marketing', purpose: 'Identifies aligned brands and drafts partnership proposal frameworks.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'medium', reputation_risk: 'high' },
  { agent_name: 'Charity Campaign Agent', group: 'marketing', purpose: 'Coordinates cause-aligned campaigns and tracks charitable impact metrics.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'low', legal_risk: 'low', reputation_risk: 'medium' },
  { agent_name: 'Pre-Save Campaign Agent', group: 'marketing', purpose: 'Builds and monitors pre-save campaigns for upcoming releases.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Promo Code Agent', group: 'marketing', purpose: 'Creates, monitors, and retires promotional codes. Flags abuse patterns.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'none' },

  // SOCIAL
  { agent_name: 'Instagram Content Agent', group: 'social', purpose: 'Drafts captions, hashtag sets, and posting schedules for Instagram.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'TikTok Strategy Agent', group: 'social', purpose: 'Develops TikTok content hooks, trending audio recommendations, and posting strategies.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'YouTube Channel Agent', group: 'social', purpose: 'Plans video upload schedules, descriptions, tags, and community posts.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Facebook Page Agent', group: 'social', purpose: 'Maintains Facebook page activity with post scheduling and community responses.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'medium' },
  { agent_name: 'Twitter/X Agent', group: 'social', purpose: 'Drafts tweet threads, quote tweets, and real-time commentary for key moments.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'high' },
  { agent_name: 'Social Listening Agent', group: 'social', purpose: 'Monitors brand mentions, tags, and fan content across all social platforms.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'UGC Amplification Agent', group: 'social', purpose: 'Identifies and queues high-quality fan-created content for resharing and acknowledgment.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'medium' },
  { agent_name: 'Content Calendar Agent', group: 'social', purpose: 'Maintains a cross-platform content calendar synced with release schedules and campaigns.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },

  // BUSINESS
  { agent_name: 'Revenue Forecasting Agent', group: 'business', purpose: 'Models revenue projections across streaming, merch, touring, and sync.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Deal Evaluation Agent', group: 'business', purpose: 'Analyses deal terms and flags unfavourable conditions in record, sync, and brand deals.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'medium' },
  { agent_name: 'Team Management Agent', group: 'business', purpose: 'Coordinates task delegation, deadlines, and accountability across the team.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Vendor Management Agent', group: 'business', purpose: 'Tracks vendors, invoices, and renewal dates for services and suppliers.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'low', reputation_risk: 'none' },
  { agent_name: 'Tour Planning Agent', group: 'business', purpose: 'Coordinates tour routing, costs, technical riders, and venue requirements.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'medium', reputation_risk: 'medium' },
  { agent_name: 'Merch Business Agent', group: 'business', purpose: 'Optimises merch pricing, monitors margins, and flags reorder needs.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'medium', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Streaming Royalties Agent', group: 'business', purpose: 'Tracks streaming performance and reconciles royalty statements across platforms.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'medium', legal_risk: 'low', reputation_risk: 'none' },
  { agent_name: 'Label Relations Agent', group: 'business', purpose: 'Manages communication and deliverable tracking with distribution and label partners.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'medium' },

  // FINANCE
  { agent_name: 'Cash Flow Monitor', group: 'finance', purpose: 'Tracks real-time cash position and flags upcoming shortfalls or large expenses.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Invoice Tracking Agent', group: 'finance', purpose: 'Monitors outstanding invoices and sends chase reminders.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'medium', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Expense Categorisation Agent', group: 'finance', purpose: 'Auto-categorises expenses and flags items requiring professional review.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'BAS & GST Agent', group: 'finance', purpose: 'Monitors Australian GST obligations and flags BAS lodgement windows.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'none' },
  { agent_name: 'Superannuation Agent', group: 'finance', purpose: 'Tracks super contributions for contractors and employees. Flags compliance gaps.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'none' },
  { agent_name: 'Charitable Giving Agent', group: 'finance', purpose: 'Tracks donation commitments, receipts, and tax-deductible giving targets.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'low', reputation_risk: 'none' },
  { agent_name: 'Wealth Protection Agent', group: 'finance', purpose: 'Monitors asset exposure, insurance coverage, and wealth preservation strategies.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'medium', reputation_risk: 'none' },

  // SYSTEMS
  { agent_name: 'Automation Integrity Agent', group: 'systems', purpose: 'Monitors all backend automations for failure, drift, and unexpected behaviour.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Data Sync Agent', group: 'systems', purpose: 'Ensures consistency between database records, Google Sheets, and external integrations.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'low', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'API Health Agent', group: 'systems', purpose: 'Monitors third-party API health (Stripe, Tunecore, Sheets) and alerts on failures.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Backup Integrity Agent', group: 'systems', purpose: 'Verifies scheduled backups completed successfully and flags gaps.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Email Deliverability Agent', group: 'systems', purpose: 'Monitors email open rates, bounces, and spam scores. Flags deliverability degradation.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'low' },
  { agent_name: 'Platform Migration Agent', group: 'systems', purpose: 'Plans and executes data migrations when platforms change or are replaced.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'medium', legal_risk: 'low', reputation_risk: 'none' },
  { agent_name: 'Idempotency Guard Agent', group: 'systems', purpose: 'Ensures no duplicate orders, payments, or critical operations are processed twice.', status: 'inactive', approval_level: 'auto', financial_risk: 'high', legal_risk: 'none', reputation_risk: 'none' },

  // SECURITY
  { agent_name: 'Access Control Agent', group: 'security', purpose: 'Monitors user roles, admin access, and flags unusual permission changes.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Fraud Detection Agent', group: 'security', purpose: 'Monitors orders and payments for fraud signals including velocity, address mismatch, and chargebacks.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'medium', reputation_risk: 'medium' },
  { agent_name: 'Data Privacy Agent', group: 'security', purpose: 'Ensures fan data handling complies with Australian Privacy Act and GDPR.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Phishing & Impersonation Monitor', group: 'security', purpose: 'Detects fake accounts, impersonation attempts, and phishing domains using the artist brand.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Penetration Awareness Agent', group: 'security', purpose: 'Surfaces reported vulnerabilities in platform dependencies and flags required patches.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'none', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Community Safety Agent', group: 'security', purpose: 'Monitors fan community for harassment, hate speech, and safety violations.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'medium', reputation_risk: 'high' },
  { agent_name: 'Registry Repair Agent', group: 'security', purpose: 'Monitors AI OS registry visibility, count mismatches, RLS/read failures, and reseed drift. Auto-diagnoses; requires approval before deleting or reseeding records.', status: 'active', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },

  // ORCHESTRATOR
  { agent_name: 'Master Orchestrator', group: 'orchestrator', purpose: 'Central coordination agent that routes tasks, resolves conflicts, and manages inter-agent dependencies.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Priority Escalation Agent', group: 'orchestrator', purpose: 'Monitors all agent queues and escalates blocked, overdue, or high-risk items to the owner.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Decision Memory Agent', group: 'orchestrator', purpose: 'Records all major decisions, rationale, and outcomes for future context and consistency.', status: 'inactive', approval_level: 'auto', financial_risk: 'none', legal_risk: 'low', reputation_risk: 'none' },
  { agent_name: 'System Audit Agent', group: 'orchestrator', purpose: 'Periodically audits the entire AI OS for drift, orphaned automations, and coverage gaps.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
  { agent_name: 'Do-Not-Spend Enforcer', group: 'orchestrator', purpose: 'Intercepts any agent action that involves spending, legal commitment, or publishing. Blocks until owner approves.', status: 'inactive', approval_level: 'always_approve', financial_risk: 'high', legal_risk: 'high', reputation_risk: 'high' },
  { agent_name: 'Knowledge Sync Agent', group: 'orchestrator', purpose: 'Keeps the Knowledge Vault current by pulling insights from completed agent tasks.', status: 'inactive', approval_level: 'low_risk_auto', financial_risk: 'none', legal_risk: 'none', reputation_risk: 'none' },
];