// ─────────────────────────────────────────────────────────────────────────────
// STORE WORLD CONFIG
// Update BOUTIQUE_HERO_IMAGE to your uploaded Canva export path when ready.
// Hotspot percentages are relative to the hero image dimensions (left%, top%).
// ─────────────────────────────────────────────────────────────────────────────

export const BOUTIQUE_HERO_IMAGE = null; // Set to '/assets/store-boutique-hero.jpg' after upload

export const STORE_PRODUCTS = [
  {
    id: 'winter-bundle',
    name: 'Winter Writing & Comfort Bundle',
    price: '$129',
    priceNote: 'plus postage',
    status: 'available',
    badge: 'BUNDLE',
    link: '/store',
    anchor: '#winter-bundle',
    tooltip: 'Journal · Pen · Thermos · Hoodie & more',
    zone: 'Centre Pedestal — Hero Display',
    hotspot: { x: 38, y: 35, width: 24, height: 30 },
  },
  {
    id: 'journal-bundle',
    name: 'Thankyou Journal, Pen and Thermos Flask Bundle',
    price: '$59',
    priceNote: 'plus postage',
    status: 'available',
    badge: null,
    link: '/store',
    anchor: '#journal-bundle',
    tooltip: 'The Thankyou trio — journal, pen & flask',
    zone: 'Left Display Zone',
    hotspot: { x: 10, y: 40, width: 20, height: 24 },
  },
  {
    id: 'hoodie',
    name: 'Thankyou "Respect Is Earned" Oversized Hoodie — Dark Grey',
    price: '$89',
    priceNote: 'plus postage',
    status: 'available',
    badge: 'NEW',
    link: '/store',
    anchor: '#hoodie',
    tooltip: 'Premium oversized dark grey hoodie',
    zone: 'Hoodie Rail — Right',
    hotspot: { x: 66, y: 25, width: 18, height: 40 },
  },
  {
    id: 'mug',
    name: 'Thankyou "Respect Is Earned" Coffee Mug',
    price: '$9.90',
    priceNote: 'plus postage',
    status: 'available',
    badge: null,
    link: '/store',
    anchor: '#mug',
    tooltip: 'Ceramic coffee mug — Respect Is Earned',
    zone: 'Counter Display',
    hotspot: { x: 68, y: 65, width: 14, height: 16 },
  },
  {
    id: 'poster',
    name: 'Thankyou "Respect Is Earned" Wall Poster',
    price: 'From $19',
    priceNote: 'A4 · A3 · A2 · A1',
    status: 'available',
    badge: 'LIMITED',
    link: '/store',
    anchor: '#poster',
    tooltip: 'Limited edition wall poster — multiple sizes',
    zone: 'Poster Wall — Feature Wall',
    hotspot: { x: 82, y: 10, width: 14, height: 55 },
  },
  {
    id: 'cd',
    name: 'CD & Music Collectables',
    price: null,
    priceNote: null,
    status: 'sold_out',
    badge: 'SOLD OUT',
    link: '/store',
    anchor: '#cd',
    tooltip: 'Signed CDs & music collectables',
    zone: 'Music Corner',
    hotspot: { x: 52, y: 68, width: 14, height: 16 },
  },
  {
    id: 'tote',
    name: 'Gannon Waye Tote Bag',
    price: null,
    priceNote: null,
    status: 'sold_out',
    badge: 'SOLD OUT',
    link: '/store',
    anchor: '#tote',
    tooltip: 'Sold out — demand was incredible 🤍',
    zone: 'Accessories Shelf',
    hotspot: { x: 3, y: 62, width: 8, height: 16 },
  },
  {
    id: 'mums-garden',
    name: "Mum's Garden",
    price: null,
    priceNote: null,
    status: 'memorial',
    badge: '♡',
    link: '/mums-garden',
    anchor: '',
    tooltip: 'A quiet corner — always in our hearts',
    zone: "Tribute Corner — Mum's Garden",
    hotspot: { x: 2, y: 30, width: 9, height: 18 },
  },
];