export const BOUTIQUE_HERO_IMAGE = "/images/store/high_end_merch_store_for_gannon_waye.png";

export const STORE_PRODUCTS = [
  {
    id: "front-hoodie",
    name: 'Thankyou "Respect Is Earned" Oversized Hoodie — Front Print',
    shortName: "Front Print Hoodie",
    tooltip: "Shop the front print hoodie",
    price: "$89",
    priceValue: 89,
    priceNote: "+ postage",
    status: "available",
    badge: "Hoodie",
    category: "hoodies",
    link: "/store/product/thankyou-respect-is-earned-hoodie-front",
    images: ["/images/products/hoodie-front.png", "/images/products/hoodie-back.png"],
    description: "Dark grey oversized hoodie featuring the Thankyou artwork on the front with Gannon Waye signature detail. A wearable piece from the Respect Is Earned collection.",
    options: { size: ["S", "M", "L", "XL", "2XL", "3XL"] },
    addons: ["mug-addon", "poster-addon"],
    hotspot: { left: "3%", top: "35%", width: "20%", height: "45%" }
  },
  {
    id: "back-hoodie",
    name: 'Thankyou "Respect Is Earned" Oversized Hoodie — Back Print',
    shortName: "Back Print Hoodie",
    tooltip: "Shop the back print hoodie",
    price: "$89",
    priceValue: 89,
    priceNote: "+ postage",
    status: "available",
    badge: "Hoodie",
    category: "hoodies",
    link: "/store/product/thankyou-respect-is-earned-hoodie-back",
    images: ["/images/products/hoodie-back.png", "/images/products/hoodie-front.png"],
    description: "Dark grey oversized hoodie with the lyric line Respect Is Earned, Not A Game You Make Me Play across the back. Designed as a statement piece from Thankyou.",
    options: { size: ["S", "M", "L", "XL", "2XL", "3XL"] },
    addons: ["mug-addon", "poster-addon"],
    hotspot: { left: "78%", top: "38%", width: "20%", height: "47%" }
  },
  {
    id: "winter-writing-comfort-bundle",
    name: "Winter Writing & Comfort Bundle",
    shortName: "Winter Bundle",
    tooltip: "Shop the hero winter bundle",
    price: "$129",
    priceValue: 129,
    priceNote: "+ postage",
    status: "available",
    badge: "Featured Bundle",
    category: "bundles",
    excludeFromDiscounts: true,
    link: "/store/product/winter-writing-comfort-bundle",
    images: ["/images/products/winter-writing-comfort-bundle.png", "/images/products/journal-pen-thermos-bundle.png", "/images/products/hoodie-front.png", "/images/products/hoodie-back.png"],
    description: "The hero offer of the Thankyou merch store. Includes the oversized Respect Is Earned hoodie plus the Thankyou journal, pen and thermos flask bundle. Discount already marked — excluded from promo codes.",
    includes: ['Thankyou "Respect Is Earned" Oversized Hoodie', "Thankyou Journal", "Thankyou Pen", "Thankyou Thermos Flask"],
    options: { size: ["S", "M", "L", "XL", "2XL", "3XL"] },
    addons: ["mug-addon", "poster-addon"],
    hotspot: { left: "36%", top: "43%", width: "28%", height: "24%" }
  },
  {
    id: "journal-pen-thermos-bundle",
    name: "Thankyou Journal, Pen & Thermos Flask Bundle",
    shortName: "Journal, Pen & Thermos",
    tooltip: "Shop the writing bundle",
    price: "$59",
    priceValue: 59,
    priceNote: "+ postage",
    status: "available",
    badge: "Bundle",
    category: "bundles",
    excludeFromDiscounts: true,
    link: "/store/product/journal-pen-thermos-bundle",
    images: ["/images/products/journal-pen-thermos-bundle.png", "/images/products/thermos.png", "/images/products/journal.png"],
    description: "A premium Thankyou writing set featuring the Respect Is Earned journal, matching pen and thermos flask. Designed for reflection, writing, healing and comfort.",
    addons: ["mug-addon", "poster-addon"],
    hotspot: { left: "54%", top: "43%", width: "18%", height: "24%" }
  },
  {
    id: "mug",
    name: 'Thankyou "Respect Is Earned" Coffee Mug',
    shortName: "Coffee Mug",
    tooltip: "Shop the mug collection",
    price: "$9.90",
    priceValue: 9.90,
    priceNote: "+ postage",
    status: "available",
    badge: "Mug",
    category: "mugs",
    link: "/store/product/thankyou-respect-is-earned-coffee-mug",
    images: ["/images/products/mug-front.png", "/images/products/mug-back.png"],
    description: "Ceramic Thankyou coffee mug featuring the Respect Is Earned lyric artwork. A simple daily reminder from the song.",
    addons: ["poster-addon"],
    hotspot: { left: "34%", top: "64%", width: "36%", height: "12%" }
  },
  {
    id: "wall-poster",
    name: 'Thankyou "Respect Is Earned" Wall Poster',
    shortName: "Wall Poster",
    tooltip: "Shop lyric wall posters",
    price: "From $39",
    priceValue: 39,
    priceNote: "assorted sizes",
    status: "available",
    badge: "Poster",
    category: "posters",
    link: "/store/product/thankyou-respect-is-earned-wall-poster",
    images: ["/images/products/poster-respect-is-earned.png", "/images/products/poster-thankyou-halo.png", "/images/products/poster-choosing-peace.png", "/images/products/poster-no-game-anymore.png"],
    description: "Premium Thankyou lyric wall poster. Assorted sizing available, with pricing varying by size.",
    options: { size: ["A4", "A3", "A2", "A1"] },
    addons: ["mug-addon"],
    hotspot: { left: "24%", top: "22%", width: "52%", height: "20%" }
  },
  {
    id: "cd",
    name: "Thankyou CD",
    shortName: "CD Collection",
    tooltip: "View CD collection",
    price: "Sold Out",
    priceValue: 0,
    status: "sold_out",
    badge: "Sold Out",
    category: "collectables",
    link: "/store/product/thankyou-cd",
    images: ["/images/products/cd-cover.png", "/images/products/cd-open.png"],
    description: "Thankyou physical CD collectable. Currently sold out.",
    hotspot: { left: "32%", top: "77%", width: "24%", height: "13%" }
  },
  {
    id: "tote-bag",
    name: "Thankyou Tote Bag",
    shortName: "Tote Bag",
    tooltip: "View tote bag",
    price: "Sold Out",
    priceValue: 0,
    status: "sold_out",
    badge: "Sold Out",
    category: "bags",
    link: "/store/product/thankyou-tote-bag",
    images: ["/images/products/tote-bag.png"],
    description: "Thankyou tote bag featuring campaign artwork and signature detail. Currently sold out.",
    hotspot: { left: "67%", top: "77%", width: "13%", height: "13%" }
  },
  {
    id: "mums-garden",
    name: "Mum's Garden",
    shortName: "Mum's Garden",
    tooltip: "Private memorial space",
    price: "Tribute",
    status: "memorial",
    badge: "Private",
    category: "tribute",
    link: "/mums-garden",
    images: ["/images/store/mums-garden-preview.png"],
    description: "A private tribute space connected to Mum's Garden.",
    hotspot: { left: "82%", top: "18%", width: "15%", height: "23%" }
  }
];

export const STORE_ADDONS = [
  {
    id: "mug-addon",
    name: 'Add Thankyou "Respect Is Earned" Mug',
    price: "$10",
    priceValue: 10,
    image: "/images/products/mug-front.png"
  },
  {
    id: "poster-addon",
    name: 'Add Thankyou "Respect Is Earned" Poster',
    price: "$39",
    priceValue: 39,
    image: "/images/products/poster-respect-is-earned.png"
  }
];